// Copyright 2008, 2009, 2011 Global Virtual Airlines Group. All Rights Reserved.
package org.deltava.acars.message.mp;

import org.deltava.acars.message.*;

import org.deltava.beans.Pilot;

/**
 * A message sent when a user disconnects from a multi-player session. Unlike most
 * ACARS messages, this is <i>NEVER</i> generated by the client, and is used internally
 * by the server. This is the MP equivalent of the {@link QuitMessage}.
 * @author Luke
 * @version 4.1
 * @since 2.2
 */

public class RemoveMessage extends AbstractMessage {
	
	private int _flightID;
	
	/**
	 * Initializes the message.
	 * @param msgFrom the originating Pilot
	 * @param flightID the ACARS flight ID
	 */
	public RemoveMessage(Pilot msgFrom, int flightID) {
		super(Message.MSG_MPREMOVE, msgFrom);
		setProtocolVersion(2);
		_flightID = Math.max(0, flightID);
	}
	
	/**
	 * Returns the ACARS flight ID for this update.
	 * @return the flight ID
	 */
	public int getFlightID() {
		return _flightID;
	}
}