// Copyright 2008 Global Virtual Airlines Group. All Rights Reserved.
package org.deltava.acars.message.mp;

import org.deltava.acars.message.*;

import org.deltava.beans.Pilot;

/**
 * A message sent when a user disconnects from a multi-player session. Unlike most
 * ACARS messages, this is <i>NEVER</i> generated by the client, and is used internally
 * by the server. This is the MP equivalent of the {@link QuitMessage}.
 * @author Luke
 * @version 2.2
 * @since 2.2
 */

public class RemoveMessage extends AbstractMessage {
	
	/**
	 * Initializes the message.
	 * @param msgFrom the originating Pilot
	 */
	public RemoveMessage(Pilot msgFrom) {
		super(Message.MSG_MPREMOVE, msgFrom);
	}
}