CREATE TABLE CHANNELS (
 ID				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME			VARCHAR(36) NOT NULL,
 DESCRIPTION	VARCHAR(128) NOT NULL,
 RATE			SMALLINT UNSIGNED NOT NULL DEFAULT 11025,
 LAT			DECIMAL (9,4) NOT NULL,
 LNG			DECIMAL (9,4) NOT NULL,
 RNG			SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 ISDEFAULT		BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ID),
 CONSTRAINT UNIQUE (NAME)
);
