CREATE TABLE CHANNEL_ROLES (
 ID				INTEGER UNSIGNED NOT NULL,
 ROLE			VARCHAR(32) NOT NULL,
 TYPE			TINYINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID, ROLE),
 FOREIGN KEY (ID) REFERENCES CHANNELS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);