CREATE TABLE CHANNEL_AIRLINES (
 ID				INTEGER UNSIGNED NOT NULL,
 CODE			VARCHAR(3) NOT NULL,
 PRIMARY KEY (ID, CODE),
 FOREIGN KEY (ID) REFERENCES CHANNELS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (CODE) REFERENCES common.AIRLINEINFO(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);