CREATE TABLE GATEDATA (
 ID						INTEGER UNSIGNED NOT NULL,
 ICAO					CHAR(4) NOT NULL,
 GATE					VARCHAR(16) NOT NULL,
 LATITUDE               DECIMAL (7,4) NOT NULL DEFAULT 0,
 LONGITUDE              DECIMAL (7,4) NOT NULL DEFAULT 0,
 LL                     POINT SRID 4326,
 ISDEPARTURE			BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ID, ISDEPARTURE),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE
);

CREATE INDEX GATEDATA_ID_IDX ON GATEDATA(ICAO,GATE);