CREATE TABLE FLIGHT_DISPATCH_LOG (
 ID                     INTEGER UNSIGNED NOT NULL,
 LOG_ID                 INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (LOG_ID) REFERENCES DISPATCH_LOG(ID) ON UPDATE CASCADE ON DELETE CASCADE
);