CREATE TABLE FLIGHT_SIDSTAR_WP (
 ID					INTEGER UNSIGNED NOT NULL,
 TYPE				TINYINT UNSIGNED NOT NULL,
 SEQ				TINYINT UNSIGNED NOT NULL,
 CODE				VARCHAR(8) NOT NULL,
 WPTYPE				TINYINT UNSIGNED NOT NULL DEFAULT 3,
 LATITUDE			DECIMAL (10,6) NOT NULL,
 LONGITUDE			DECIMAL (10,6) NOT NULL,
 REGION				VARCHAR(3),
 PRIMARY KEY (ID, TYPE, SEQ),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);