CREATE TABLE TAXI_TIMES (
 ICAO                   CHAR(4) NOT NULL,
 APPCODE                CHAR(3) NOT NULL,
 TAXI_IN                INTEGER UNSIGNED NOT NULL DEFAULT 0,
 TAX_OUT                INTEGER UNSIGNED NOT NULL DEFAULT 0,
 TOTAL_IN               INTEGER UNSIGNED NOT NULL DEFAULT 0,
 TOTAL_OUT              INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ICAO, APPCODE),
 FOREIGN KEY (ICAO) REFERENCES common.AIRPORTS(ICAO) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (APPCODE) REFERENCES common.AIRLINEINFO(CODE) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET latin1;