CREATE TABLE FRAMERATES (
 ID                INTEGER UNSIGNED NOT NULL,
 SIZE              INTEGER UNSIGNED NOT NULL,
 MIN               SMALLINT UNSIGNED NOT NULL,
 MAX               SMALLINT UNSIGNED NOT NULL,
 P1                SMALLINT UNSIGNED NOT NULL,
 P5                SMALLINT UNSIGNED NOT NULL,
 P50               SMALLINT UNSIGNED NOT NULL,
 P95               SMALLINT UNSIGNED NOT NULL,
 P99               SMALLINT UNSIGNED NOT NULL,
 AVERAGE           DECIMAL(4,1) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET latin1;