CREATE TABLE FLIGHT_DISPATCH (
 ID						INTEGER UNSIGNED NOT NULL,
 DISPATCHER_ID			INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (DISPATCHER_ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE
);