CREATE TABLE ROUTE_WP (
 ID					INTEGER UNSIGNED NOT NULL,
 SEQ				SMALLINT UNSIGNED NOT NULL,
 CODE				VARCHAR(11) NOT NULL,
 ITEMTYPE			TINYINT UNSIGNED NOT NULL,
 LATITUDE			DECIMAL (10,6) NOT NULL,
 LONGITUDE			DECIMAL (10,6) NOT NULL,
 AIRWAY				VARCHAR(10),
 REGION				VARCHAR(3),
 PRIMARY KEY (ID, SEQ),
 FOREIGN KEY (ID) REFERENCES ROUTES(ID) ON DELETE CASCADE ON UPDATE CASCADE
);