CREATE TABLE POSITION_ATC (
 FLIGHT_ID			INTEGER UNSIGNED NOT NULL,
 REPORT_TIME		DATETIME(3) NOT NULL,
 IDX				TINYINT UNSIGNED NOT NULL DEFAULT 1,
 COM1				VARCHAR(9) NOT NULL,
 CALLSIGN			VARCHAR(16) NOT NULL,
 NETWORK_ID			INTEGER UNSIGNED NOT NULL,
 LAT				DECIMAL (7,4) NOT NULL,
 LNG				DECIMAL (7,4) NOT NULL,
 PRIMARY KEY (FLIGHT_ID, REPORT_TIME, IDX),
 FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);