CREATE TABLE ARCHIVE (
 ID         INTEGER UNSIGNED NOT NULL,
 CNT        SMALLINT UNSIGNED NOT NULL,
 SIZE       INTEGER UNSIGNED NOT NULL DEFAULT 0,
 CRC        INTEGER UNSIGNED NOT NULL DEFAULT 0,
 ARCHIVED   DATETIME NOT NULL,
 PRIMARY KEY (ID));
