CREATE TABLE CONS (
 ID					BIGINT UNSIGNED NOT NULL,
 PILOT_ID			INTEGER UNSIGNED NOT NULL,
 DATE				DATETIME NOT NULL,
 REMOTE_ADDR		INTEGER UNSIGNED NOT NULL,
 REMOTE_HOST    	VARCHAR(128) NOT NULL,
 CLIENT_BUILD		SMALLINT NOT NULL DEFAULT 0,
 BETA_BUILD			SMALLINT NOT NULL DEFAULT 0,
 PRIMARY KEY(id),
 FOREIGN KEY (PILOT_ID) REFERENCES common.USERDATA(ID)
);