CREATE TABLE FLIGHT_LOAD (
 ID                   INTEGER UNSIGNED NOT NULL,
 PAX                  SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 SEATS                SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 LOADTYPE             TINYINT UNSIGNED NOT NULL DEFAULT 0,
 LOADFACTOR           NUMERIC(5,4) NOT NULL DEFAULT -1,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;