CREATE TABLE POSITION_ATC (
 FLIGHT_ID			INTEGER UNSIGNED NOT NULL,
 REPORT_TIME		DATETIME NOT NULL,
 TIME_MS			SMALLINT UNSIGNED NOT NULL,
 COM1				VARCHAR(9) NOT NULL,
 CALLSIGN			VARCHAR(16) NOT NULL,
 NETWORK_ID			INTEGER UNSIGNED NOT NULL,
 LAT				DECIMAL (7,4) NOT NULL,
 LNG				DECIMAL (7,4) NOT NULL,
 PRIMARY KEY (FLIGHT_ID, REPORT_TIME, TIME_MS),
 FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);