CREATE TABLE LIVERIES (
 AIRLINE			CHAR(3) NOT NULL,
 LIVERY				VARCHAR(8) NOT NULL,
 NAME				VARCHAR(80) NOT NULL,
 ISDEFAULT			BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (AIRLINE, LIVERY),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE
);