CREATE TABLE POS_ARCHIVE (
 ID					INTEGER UNSIGNED NOT NULL,
 CNT				SMALLINT UNSIGNED NOT NULL,
 ARCHIVED			DATETIME NOT NULL,
 DATA				MEDIUMBLOB,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4;

CREATE INDEX POSARC_DT_IDX ON POS_ARCHIVE(ARCHIVED);
