CREATE TABLE TRACKS (
 X				INTEGER UNSIGNED NOT NULL,
 Y				INTEGER UNSIGNED NOT NULL,
 Z				INTEGER UNSIGNED NOT NULL,
 SIZE			INTEGER UNSIGNED NOT NULL,
 IMG			MEDIUMBLOB NOT NULL,
 PRIMARY KEY (X, Y, Z)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;