CREATE TABLE SYSINFO (
 ID                         INTEGER UNSIGNED NOT NULL,
 CREATED                    DATETIME NOT NULL,
 OS_VERSION                 VARCHAR(64) NOT NULL,
 CLR_VERSION                VARCHAR(24) NOT NULL,
 NET_VERSION                VARCHAR(24) NOT NULL,
 IS64                       BOOLEAN NOT NULL DEFAULT FALSE,
 SLI                        BOOLEAN NOT NULL DEFAULT FALSE,
 LOCALE                     VARCHAR(12) NOT NULL,
 TZ                         VARCHAR(64) NOT NULL,
 MEMORY                     INTEGER UNSIGNED NOT NULL,
 CPU                        VARCHAR(48) NOT NULL,
 CPU_SPEED                  SMALLINT UNSIGNED NOT NULL,
 CPU_SOCK                   SMALLINT UNSIGNED NOT NULL,
 CPU_CORE                   SMALLINT UNSIGNED NOT NULL,
 CPU_PROC                   SMALLINT UNSIGNED NOT NULL,
 GPU                        VARCHAR(48) NOT NULL,
 GPU_DRIVER                 VARCHAR(32) NOT NULL,
 VRAM                       SMALLINT UNSIGNED NOT NULL,
 X                          SMALLINT UNSIGNED NOT NULL,
 Y                          SMALLINT UNSIGNED NOT NULL,
 BPP                        TINYINT UNSIGNED NOT NULL,
 SCREENS                    TINYINT UNSIGNED NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);