CREATE TABLE FLIGHT_DISPATCH (
 ID						INTEGER UNSIGNED NOT NULL,
 ROUTE_ID				INTEGER UNSIGNED NOT NULL,
 DISPATCHER_ID			INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES(ID) ON UPDATE CASCADE
);