CREATE TABLE ERRORS (
 ID							INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 USERID						INTEGER UNSIGNED NOT NULL,
 CREATED_ON					DATETIME NOT NULL,
 REMOTE_ADDR				INTEGER UNSIGNED NOT NULL,
 REMOTE_HOST				VARCHAR(144) NOT NULL,
 CLIENT_BUILD				SMALLINT UNSIGNED NOT NULL,
 FS_VERSION					SMALLINT UNSIGNED,
 FSUIPC_VERSION				DECIMAL(4,3),
 ERROR_MSG					VARCHAR(244) NOT NULL,
 STACKDUMP					MEDIUMTEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (USERID) REFERENCES common.USERDATA(ID)
);