CREATE TABLE BANDWIDTH (
 PERIOD						DATETIME NOT NULL,
 DURATION					INTEGER UNSIGNED NOT NULL DEFAULT 1,
 CONS							SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 BYTES_IN					INTEGER UNSIGNED NOT NULL,
 BYTES_OUT				INTEGER UNSIGNED NOT NULL,
 MSGS_IN						INTEGER UNSIGNED NOT NULL,
 MSGS_OUT					INTEGER UNSIGNED NOT NULL,
 PEAK_CONS				INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PEAK_BYTES				INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PEAK_MSGS				INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (PERIOD)
);