CREATE TABLE LIVERIES (
 AIRLINE			VARCHAR(3) NOT NULL,
 LIVERY				VARCHAR(8) NOT NULL,
 NAME				VARCHAR(80) NOT NULL,
 ISDEFAULT			BOOLEAN DEFAULT FALSE,
 PRIMARY KEY (AIRLINE, LIVERY),
 FOREIGN KEY (CODE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE
);