CREATE TABLE TOLAND (
 ID					INTEGER UNSIGNED NOT NULL,
 TAKEOFF			BOOLEAN NOT NULL DEFAULT FALSE,
 EVENT_TIME			DATETIME NOT NULL,
 PRIMARY KEY (ID, TAKEOFF),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
