CREATE TABLE SIMINFO (
 ID                         INTEGER UNSIGNED NOT NULL,
 CREATED                    DATETIME NOT NULL,
 SIM                        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 BRIDGE                     VARCHAR(32) NOT NULL,
 PRIMARY KEY (ID, SIM),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);