CREATE TABLE FLIGHT_SIDSTAR_WP (
 ID					INTEGER UNSIGNED NOT NULL,
 TYPE				TINYINT UNSIGNED NOT NULL,
 SEQ				TINYINT UNSIGNED NOT NULL,
 CODE				VARCHAR(8) NOT NULL,
 LATITUDE			DECIMAL (10,6) NOT NULL,
 LONGITUDE			DECIMAL (10,6) NOT NULL,
 PRIMARY KEY (ID, TYPE, SEQ),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);