CREATE TABLE TAXI_TIMES (
 ID                     INTEGER UNSIGNED NOT NULL,
 IS_DEPARTURE           BOOLEAN NOT NULL DEFAULT FALSE,
 IATA                   CHAR(3) NOT NULL,
 YEAR                   SMALLINT UNSIGNED NOT NULL,
 TAXITIME               SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID, IS_DEPARTURE),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (IATA) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;

CREATE INDEX TAXI_APYR_IDX ON TAXI_TIMES(IATA, IS_DEPARTURE, YEAR);