CREATE TABLE CONS (
 ID				BIGINT UNSIGNED NOT NULL,
 PILOT_ID		INTEGER UNSIGNED NOT NULL,
 DATE			DATETIME NOT NULL,
 REMOTE_ADDR	INTEGER UNSIGNED NOT NULL,
 REMOTE_HOST    VARCHAR(128) NOT NULL,
 PRIMARY KEY(id),
 FOREIGN KEY (PILOT_ID) REFERENCES COMMON.USERDATA(ID)
);