CREATE TABLE RWYDATA (
 ID						INTEGER UNSIGNED NOT NULL,
 ICAO					CHAR(4) NOT NULL,
 RUNWAY					VARCHAR(3) NOT NULL,
 LATITUDE				DECIMAL (10,6) NOT NULL,
 LONGITUDE				DECIMAL (10,6) NOT NULL,
 LENGTH					SMALLINT UNSIGNED NOT NULL,
 DISTANCE				SMALLINT UNSIGNED NOT NULL,
 ISTAKEOFF				BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ID, ISTAKEOFF),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE
);