CREATE TABLE TRACK_AIRPORTS (
 IATA					CHAR(3) NOT NULL,
 CNT						INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (IATA),
 FOREIGN KEY (IATA) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE ON DELETE CASCADE
);