CREATE TABLE COMMAND_STATS (
 CMDDATE				DATETIME NOT NULL,
 MS						SMALLINT UNSIGNED NOT NULL,
 USERID					INTEGER UNSIGNED NOT NULL DEFAULT 0,
 CLASS					VARCHAR(32) NOT NULL,
 EXECTIME				INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (CMDDATE, MS, USERID)
);