CREATE TABLE FLIGHT_SIDSTAR (
 ID					INTEGER UNSIGNED NOT NULL,
 TYPE				TINYINT UNSIGNED NOT NULL,
 NAME				VARCHAR(16) NOT NULL,
 TRANSITION			VARCHAR(8) NOT NULL,
 RUNWAY				VARCHAR(8) NOT NULL,
 PRIMARY KEY (ID, TYPE),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);