CREATE TABLE WARNINGS (
 ID					INTEGER UNSIGNED NOT NULL,
 AUTHOR				INTEGER UNSIGNED NOT NULL,
 WARNED_ON			DATETIME NOT NULL,
 SCORE				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID, AUTHOR),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES common.USERDATA(ID) ON DELETE CASCADE ON UPDATE CASCADE
);