CREATE TABLE PERFINFO (
 ID                INTEGER UNSIGNED NOT NULL,
 TIMER             VARCHAR(48) NOT NULL,
 TICKSIZE          INTEGER UNSIGNED NOT NULL DEFAULT 10000,
 COUNT             INTEGER UNSIGNED NOT NULL DEFAULT 0,
 TOTAL             INTEGER UNSIGNED NOT NULL DEFAULT 0,
 MIN               INTEGER UNSIGNED NOT NULL DEFAULT 0,
 MAX               INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID, TIMER),
 FOREIGN KEY (ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=latin1;